version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - defaultnetwork
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: http-server dist
    ports:
      - "8080:8080"
    networks:
      - defaultnetwork

networks:
  defaultnetwork:
    driver: bridge