name: Remote SSH deploy

on:
  push:
    branches: [ production ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: freqbot ssh deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            bash pull_and_reload.sh
          host: ${{ secrets.HOST }}
          user: ubuntu
          key: ${{ secrets.PRIVATE_KEY}}

          args: "-tt -vvv"